version: "2"
services:
  app:
    container_name: easy-homeworks-back-dev
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
