version: "2"
services:
  app:
    container_name: easy-homeworks-back-prod
    build:
      context: ./
      dockerfile: ./infra/Dockerfile.dev
    ports:
      - 8080:8081
    volumes:
      - ./src:/app/src
